mysite/urls.py
# mysite/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.conf.urls.i18n import i18n_patterns
from search import views as search_views
from .api import api_router

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("api/v2/", api_router.urls),
    path("subscribe/", include('subscribe.urls')),
    path('django-rq/', include('django_rq.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + i18n_patterns(
    path("search/", search_views.search, name="search"),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
)

subscribe/urls.py
# subscribe/urls.py
from django.urls import path
from . import views

app_name = 'subscribe'

urlpatterns = [
    path('new/', views.subscribe, name='new'), # Changed from 'subscribe/' to 'new/'
    path('success/', views.subscribe_success, name='subscribe_success'),
]

subscribe/models.py
# subscribe/models.py
from django.db import models

class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    nickname = models.CharField(max_length=255, blank=True,
                                default="anonymous")  # Default name set to 'anonymous' Added field, blank=True allows the field to be optional
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.nickname} <{self.email}>" if self.nickname else self.email

subscribe/forms.py
# subscribe/forms.py
from django import forms
from .models import Subscriber

class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ('email',)

subscribe/views.py
# subscribe/views.py

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import SubscriberForm
from django.shortcuts import redirect

def subscribe(request):
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('subscribe:subscribe_success'))
    else:
        form = SubscriberForm()

    return render(request, 'subscribe_page.html', {'form': form})

def subscribe_success(request):
    return render(request, 'subscribe_success.html')

mysite/templates/base.html
{% load static wagtailcore_tags wagtailuserbar %}
{% load i18n wagtailcore_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
            {% if page.seo_title %}{{ page.seo_title }}{% else %}{{ page.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
            {% wagtail_site as current_site %}
            {% if current_site and current_site.site_name %}- {{ current_site.site_name }}{% endif %}
            {% endblock %}
        </title>
        <meta charset="UTF-8" />
        <link rel="apple-touch-icon" sizes="180x180" href="static/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="static/favicon-32x32.png">
       <link rel="icon" type="image/png" sizes="16x16" href="static/favicon-16x16.png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
            integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
            crossorigin="anonymous" referrerpolicy="no-referrer" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

        {% block extra_css %}
        {# extra stylesheets #}
        {% endblock %}
    </head>

    <body>
        {% wagtailuserbar %}
        <div id="root"></div>

        {% block content %}
        
        {% endblock %}

        {# Global javascript #}
        {% comment %} <script type="text/javascript" src="{% static 'js/mysite.js' %}"></script> {% endcomment %}

        {% block extra_js %}
        {#  extra javascript #}
        {% endblock %}
    </body>
</html>

mysite/templates/blog_base.html
{% load static wagtailcore_tags wagtailuserbar %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>
        {% block title %}
            {% if page.seo_title %}
                {{ page.seo_title }}
            {% else %}
                {{ page.title }}
            {% endif %}
        {% endblock %}
    </title>
    <meta charset="UTF-8"/>
    <link rel="apple-touch-icon"
          sizes="180x180"
          href="/static/apple-touch-icon.png">
    <link rel="icon"
          type="image/png"
          sizes="32x32"
          href="/static/favicon-32x32.png">
    <link rel="icon"
          type="image/png"
          sizes="16x16"
          href="/static/favicon-16x16.png">
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
          integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {# Global stylesheets #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    {% block extra_css %}{# extra stylesheets #}{% endblock %}
</head>
<body>

{% include 'language_menu.html' %}


{% include 'wallet.html' %}

<div class="flex flex-col h-screen bg-gray-100">
    {% block content %}{% endblock %}
    <section class="mt-10">
        <footer class="bg-gray-100 text-center">
            {% include 'subscribe.html' %}
            <div class="text-center text-gray-700 p-4 bg-gray-400">
                © 2023 Copyright:
                <a class="text-gray-800" href="https://aaron404.com/">changxing</a>
            </div>
        </footer>
    </section>
</div>

</body>
{% block extra_js %}{#  extra javascript #}{% endblock %}
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script"
        async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

{% wagtailuserbar %}
</html>

mysite/templates/heading.html
       <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/highlight.min.js"></script>

mysite/templates/language_menu.html
{% load i18n wagtailcore_tags %}
<div class="hidden md:flex md:space-x-4 bg-gray-50">
  {% for translation in page.get_translations.live %}
    {% get_language_info for translation.locale.language_code as lang %}
    <a href="{% pageurl translation %}" rel="alternate" hreflang="{{ lang.code }}" class="px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900">
   <i class="fa fa-shake fa-globe"></i>
      {{ lang.name_local }}
    </a>
  {% endfor %}
</div>

<div class="sm:flex md:hidden lg:hidden">
  <button id="language-switch-button" class="px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900">
   <i class="fa-solid fa-language" style="color: #00affa;"></i>
    {% get_current_language as CURRENT_LANGUAGE %}
    {% get_language_info for CURRENT_LANGUAGE as CURRENT_LANG %}
    {{ CURRENT_LANG.name_local }}
  </button>
  <div id="language-switch-dropdown" class="hidden">
    {% for translation in page.get_translations.live %}
      {% get_language_info for translation.locale.language_code as lang %}
      <a href="{% pageurl translation %}" rel="alternate" hreflang="{{ lang.code }}" class="px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900">
        {{ lang.name_local }}
      </a>
    {% endfor %}
  </div>
</div>

<script>
// Close the menu on window resize
window.addEventListener('resize', function() {
  var languageLinks = document.querySelectorAll('.hidden.md\\:flex');
  var dropdown = document.querySelector('#language-switch-dropdown');
  if (window.innerWidth < 768) {
    languageLinks.forEach(function(link) {
      link.classList.add('hidden');
    });
    dropdown.classList.add('hidden');
  } else {
    languageLinks.forEach(function(link) {
      link.classList.remove('hidden');
    });
    dropdown.classList.remove('hidden');
  }
});

// Show dropdown on button click
var languageButton = document.querySelector('#language-switch-button');
languageButton.addEventListener('click', function() {
  var dropdown = document.querySelector('#language-switch-dropdown');
  dropdown.classList.toggle('hidden');
});

// Trigger the resize event on page load
window.addEventListener('DOMContentLoaded', function() {
  window.dispatchEvent(new Event('resize'));
});
</script>

mysite/templates/share_base.html
{% extends "blog_base.html" %}
{% load static wagtailcore_tags wagtailuserbar %}
{% load i18n wagtailcore_tags %}
{% load wagtailimages_tags %}
{% block body_class %}template-blogpage{% endblock %}
{% block extra_css %}

{% endblock %}

{% block content %}
    <section id="article" class="flex-1 sm:bg-gray-50">
        <!-- Container to heading and testm blocks -->
        <img src="{{ page.cover_image.url }}" alt="{{ page.title }}"></img>
        <div class="lg:max-w-6xl max-w-2xl text-center mx-auto shadow-2xl my-10 sm:my-4 md:my-4 ">
            <!-- Heading -->
            <h2
                    class="text-3xl font-bold text-center bg-sky-500 text-white underline underline-offset-8  decoration-gray-300 decoration-1 hover:decoration-basicBlue overflow-clip ">
                {{ page.title }}
            </h2>
        </div>

        <div class="mx-5 mt-10 mb-20 pb-28 sm:mx-4 md:mx-20 lg:mx-40 xl:mx-80 shadow-2xl bg-white">
            <a href="{{ page.get_parent.url }}">
                <div class="ml-3 p-2">
                    <div
                            class=" text-center bg-gray-50 shadow-inner hover:border-basicBlue border-solid border rounded-full md:w-10 md:h-10 sm:w-5 sm:h-5 w-8 h-8">
                    </div>
                </div>
            </a>

            {% block article %}
            {% endblock %}


            <div id="QR"
                 class="grid place-items-center border border-sky-500 mx-5 mt-48 mb-20 pb-28 sm:mx-4 md:mx-20 lg:mx-40 xl:mx-80 shadow-2xl bg-white">
                <div id="qrcode" class="mt-10 mx-auto"></div>
                <div class="text-center mt-10">长按识别或扫描此二维码查看博文原址</div>
            </div>
    </section>
    {% block extra_share_things %}
{% endblock %}
    <div class="grid h-screen place-items-center">
        <button id="generate" type="button"
                class="inline-bloc mx-auto px-6 py-2.5 bg-slate-50 text-basicBlue font-medium text-xs  active:shadow-lg transition duration-150 ease-in-out">
            Generate
        </button>
    </div>

    {{ slugurl }}
{% endblock %}



{% block extra_js %}
    <script src="{% static 'js/mathconfig.js' %}" type="text/javascript"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
    <script>
        qrtext = $(location).attr('href').split('?')[0]
        const reg = /(?:\/zh-hans\/|\/en\/)/
        qrtext = qrtext.replace(reg, '/')
        new QRCode(document.getElementById("qrcode"), qrtext);

        $(document).ready(function () {
            {% comment %} hljs.highlightAll(); {% endcomment %}
            $("#generate").click(function () {
                var node = document.getElementById('article');
                let scale = 2;
                let style = {
                    transform: `scale(${scale})`,
                    transformOrigin: 'top left',
                    // width: node.clientWidth + 'px', // use original width of DOM element to avoid part of the image being cropped out
                    // height: node.clientHeight + 'px' // use original height of DOM element
                };
                domtoimage.toBlob(node, {
                    width: node.clientWidth * scale,
                    height: node.clientHeight * scale,
                    style: style
                })
                    .then(function (blob) {
                        window.saveAs(blob, 'share.png');
                    });
            })
        })
    </script>
{% endblock %}

mysite/templates/subscribe.html
{% load static %}
<div class="max-w-4xl mx-auto flex items-center justify-center py-6">
    <form action="{% url 'subscribe:new' %}" method="post" class="grid grid-cols-1 md:grid-cols-2 gap-6">

        {% csrf_token %}
        <div class="flex items-center justify-center md:justify-start">
            <div class="flex items-center justify-center mx-2 md:justify-start text-3xl text-sky-500">
                <i class="fas fa-star fa-bounce"></i>
            </div>
            <input
                    type="text"
                    name="email"
                    class="form-input mr-2 md:mt-0 block w-full px-4 py-4 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500 text-xl border-gray-300"
                    id="exampleFormControlInput1"
                    placeholder="Email address"
            />
        </div>

        {% if subscribe_form.errors %}
            <div class="text-red-600">
                <strong>Error!</strong> {{ subscribe_form.errors }}
            </div>
        {% endif %}

        <button
                type="submit"
                class="flex justify-center py-4 px-4 md:px-2 border rounded-md shadow-md font-medium bg-sky-500 text-white hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 col-span-2 md:col-span-1"
        >
            Subscribe
        </button>
    </form>
</div>

mysite/templates/subscribe_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Subscription Success</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <div class="flex flex-col items-center justify-center min-h-screen text-gray-600 antialiased bg-gray-100">
        <div class="relative sm:max-w-xl sm:mx-auto">
            <div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20 ring-1 ring-black ring-opacity-5">
                <h1 class="text-2xl font-bold text-center">
                    Subscription Successful
                </h1>
                <div class="divide-y divide-gray-200">
                    <p class="mt-6 text-sm text-center text-gray-500">
                        Thank you for subscribing! We'll start sending updates to your email soon.
                    </p>
                    <div class="mt-8 flex items-center justify-center">
                        <a href="/" class="px-4 py-2 font-semibold text-white transition duration-500 ease-in-out transform bg-blue-600 rounded hover:bg-blue-800 focus:shadow-outline focus:outline-none focus:ring-2 ring-offset-current ring-offset-2">Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

mysite/templates/wallet.html
<head><script defer="defer" src="/static/js/main.62b71d64.js"></script><link href="/static/css/main.d7cb9a48.css" rel="stylesheet"></head><div id="wallet"></div>